### ISSUE TITLE
UnexpectedValueException Invalid route action: [Connections] to all routes

### ISSUE THREAD

**Issue by adoniasovidio** [DirectoryTree/LdapRecord-Browser#1]
I can't access, all routes don't work!
Instalattion Windows
PHP 7.4.28
Laravel 8
LdapRecord 2.15

`Connections` was not found.
Controller class Connections for one of your routes was not found. Are you sure this controller exists and is imported correctly?

**Comment by stevebauman** [comment]
Hi @adoniasovidio,

Can you post your `routes/web.php` file?

**Comment by adoniasovidio** [comment]
Forgive me if you don't understand your instructions in "readme.md"
But wherever I put these routes, the same error appears

![image](https://user-images.githubusercontent.com/21243126/162723434-8179a9eb-fcfb-4201-9e23-8aff67110158.png)

**Comment by stevebauman** [comment]
Hi @adoniasovidio,

You do not need to register those 3 routes, you only need to call `Browser::routes()`:

```diff
+ Route::prefix('/ldap')->group(function () {
+    \LdapRecord\Browser\Browser::routes();
+ });

- Route::get('/', Connections::class)->name('ldap::connections');
- Route::get('/{connection}', Browse::class)->name('ldap::browse');
- Route::get('/{connection}/{guid}', Browse::class)->name('ldap::show');
```

**Comment by adoniasovidio** [comment]
@stevebauman
Thanks for your help, so fast!

I believe there is a step missing, after installing with composer, there is no controller in the app/http or app/http/Controllers path

![image](https://user-images.githubusercontent.com/21243126/162753132-d6bb2e33-30e9-4981-b5dc-1b67ddfc1dc4.png)

**Comment by stevebauman** [comment]
Whoops! You're right -- can you run `composer update` and try again? I've just released an update that resolves this:

https://github.com/DirectoryTree/LdapRecord-Browser/releases/tag/v0.1.1

**Comment by adoniasovidio** [comment]
Works Perfectly, congratulations on the project and willingness to help!

**Comment by stevebauman** [comment]
Awesome! Happy to help @adoniasovidio! And thank you 😄 🙏
